name: Java CI with Gradle

on:
  push:
  pull_request:
  repository_dispatch:
    types: [run_build]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4.4.0

    - name: Fetch dependencies
      run: gradle -I gradle/support/fetchDependencies.gradle

    - name: Prepare Maven
      run: gradle prepdev

    - name: Build natives
      run: gradle buildNatives

    - name: Build with Gradle Wrapper
      run: gradle buildGhidra

  dependency-submission:

    runs-on: ubuntu-latest
    env:
      gradle-version: 8.14
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@v4.4.0
